### ISSUE TITLE
Cannot find module 'trails-smokesignals'

### ISSUE THREAD

**Issue by niallobrien** [trailsjs/trails-example-app#3]
Hi all, I just cloned this repo, ran `npm i && npm start` and received the following error:

```
Error: Cannot find module 'trails-smokesignals'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/private/var/application/my_projects/trails/trails-example-app/config/main.js:13:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by tjwebb** [comment]
Hmm, two problems here:
1. That's from before I was able to take over the `smokesignals` npm module. This is the module name now: https://www.npmjs.com/package/smokesignals. Once we change this, I will unpublish `trails-smokesignals`. The archetype is changing so quickly that this example app can't keep up. We just need to run the generator again and generate the latest version of the example app.
2. `smokesignals` should only be used when running `npm test`.

At some point, we should set up a bot that submits PRs to this repo every time the archetype changes :)
